[package]
name = "vodd"
version = "0.1.0"
edition = "2024"
authors = ["RainingComputers <vishnu.vish.shankar@gmail.com>"]


[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
yaml-rust2 = "0.10"

[dependencies]
minijinja = "2.24.0"
serde = { version = "1.0.229", features = ["derive"] }
syntect = { version = "5.3.0", default-features = false, features = ["html", "regex-fancy", "default-syntaxes"] }
tiny_http = "0.12.0"
